//Definition and Difference between variables and constants in Javascript
// A variable is any name assigned to a value in javascript and can be renamed or reassigned after being called for
// the first. 
// A constant is a type of variable which cannot be reassigned after being called
//
//
//Variables can be reassigned, changing values and names while constants cannot be reassigned
//variables can be assigned as "let" and "var" while a constant is assigned as "const"

//A javascript program that writes the name of the country as Africa and 
//its population using variables and the current year as a constant
let country = "Madagascar"
let population = 99900000 //million people
const currentYear = 2024
console.log(`The country in Africa, ${country}, has a population of ${population} in this current year of ${currentYear}!`)
